FROM ubuntu:latest

ENV LANG=C.UTF-8 LANGUAGE=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update && apt-get install -y wget iputils-ping vim gettext-base lsb-release

# OS dependencies for playwright (in case that building on rccremote is needed)
RUN apt-get install -y libxcb-shm0\
    libx11-xcb1\
    libx11-6\
    libxcb1\
    libxext6\
    libxrandr2\
    libxcomposite1\
    libxcursor1\
    libxdamage1\
    libxfixes3\
    libxi6\
    libgtk-3-0\
    libpangocairo-1.0-0\
    libpango-1.0-0\
    libatk1.0-0\
    libcairo-gobject2\
    libcairo2\
    libgdk-pixbuf-2.0-0\
    libglib2.0-0\
    libasound2t64\
    libxrender1\
    libfreetype6\
    libfontconfig1\
    libdbus-1-3\
    libnss3\
    libnspr4\
    libdrm2\
    libgbm1

RUN wget https://downloads.robocorp.com/rcc/releases/v17.28.4/linux64/rcc && wget https://downloads.robocorp.com/rcc/releases/v17.18.0/linux64/rccremote
RUN chmod +x rcc rccremote && mv rcc rccremote /usr/bin

ENTRYPOINT [ "/scripts/entrypoint-rcc.sh" ]