services:
  rccremote: &rcc
    build:
      context: .
      dockerfile: Dockerfile-rcc
    container_name: rccremote
    command: rccremote
    volumes:
      # !!! place your robot code in here
      - ./data/robots:/robots
      # !!! place your certs in here
      - ./certs:/etc/certs:ro
      # !!! place ZIP files of externally created hololibs (e.g. on Windows) in here
      - ./data/hololib_zip:/hololib_zip
      # internal stuff
      - ./scripts:/scripts
      - hololib_zip_internal:/hololib_zip_internal
      - robocorp_data:/opt/robocorp
      - robotmk_rcc_home:/opt/robotmk/rcc_home
    networks:
      - app-network

  # only uncomment for testing
  #rcc:
  #  <<: *rcc
  #  container_name: rcc
  #  command: rcc
  #  volumes:
  #    - ./scripts:/scripts
  #    - ./data/robots:/robots
  #    - ./data/robots-samples:/robots-samples
  #    - ./certs:/etc/certs:ro
  #    - ./config/rcc-profiles.d:/etc/rcc-profiles.d:ro
  #  environment:
  #    - RCC_REMOTE_ORIGIN=https://${SERVER_NAME}:${NGINX_PORT:-443}
#
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - rccremote
    volumes:
      - ./config/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./certs:/etc/nginx/certs
      - ./scripts/entrypoint-nginx.sh:/docker-entrypoint.d/entrypoint-nginx.sh
      - ./scripts/openssl.cnf.template:/openssl.cnf.template
    ports:
      - "${NGINX_PORT:-8443}:443"
    environment:
      - SERVER_NAME=${SERVER_NAME}
    networks:
      app-network:
        aliases:
          - ${SERVER_NAME}

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
  # exported hololibs from Robots in the /robots directory
  hololib_zip_internal: # the robocorp data directory of the shared holotree (where everything gets imported

  # before rccremote starts)
  robocorp_data: # the default RCC basedir where all ROBOCORP_HOMEs are set to on linux client machines. 

  # This path is the same which the Linux Scheduler sets for ROBOCORP_HOMEs on test machines. 
  robotmk_rcc_home:
